---
kind: pipeline
type: docker
name: linux-build

steps:
  - name: linux-build
    image: wowlet-linux:latest
    commands:
    - make release-static -j2

---
kind: pipeline
type: docker
name: windows-build
steps:
  - name: build
    image: wowlet-windows:latest
    commands:
    - make depends root=/depends target=x86_64-w64-mingw32 tag=win-x64 -j2

...
