#ifndef WOWLET_VERSION_H
#define WOWLET_VERSION_H

#define WOWLET_VERSION "@VERSION@"
#define WOWLET_BRANCH "@WOWLET_BRANCH@"
#define WOWLET_VERSION_SEMVER "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_REVISION@"

#define MONERO_VERSION "@MONERO_VERSION@"
#define MONERO_BRANCH "@MONERO_BRANCH@"

#define TOR_VERSION "@TOR_VERSION@"

#endif //WOWLET_VERSION_H
